In [1]:
import pandas as pd

In [2]:

# From dictionary
data = {'Name' : ['vivek','bob'],'age' : [20,25]}
df = pd.DataFrame(data)
print(df)

    Name  age
0  vivek   20
1    bob   25

In [3]:
# From list of lists
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['name','age'])
print(df)

    name  age
0  Alice   25
1    Bob   30

In [4]:
df.head()

    name  age
0  Alice   25
1    Bob   30

In [5]:
df.tail()

    name  age
0  Alice   25
1    Bob   30

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    2 non-null      object
 1   age     2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes

In [7]:
df.describe()

             age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [8]:
df['name']

0    Alice
1      Bob
Name: name, dtype: object

In [9]:
df[['name','age']]

    name  age
0  Alice   25
1    Bob   30

In [10]:
df.iloc[1]

name    Bob
age      30
Name: 1, dtype: object

In [11]:
df.loc[0]

name    Alice
age        25
Name: 0, dtype: object

In [14]:
df[df['age'] > 25]

  name  age
1  Bob   30

In [25]:
df['Gender'] = ['F' , 'M']

In [26]:
df.isnull()

    name  Gender
0  False   False
1  False   False

In [30]:
df.dropna()

    name Gender
0  Alice      F
1    Bob      M

In [31]:
df.fillna(0)

    name Gender
0  Alice      F
1    Bob      M

In [38]:
df.sort_values('Gender')

    name Gender
0  Alice      F
1    Bob      M

In [40]:
df['name'].unique()

array(['Alice', 'Bob'], dtype=object)

In [41]:
df['name'].value_counts()

name
Alice    1
Bob      1
Name: count, dtype: int64